#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.bc9ab6f21a7dcaab9245ef5cbfc9d6c4bd026925.name = "Upgrade from 12.0.0"
    test_upgrade_from.bc9ab6f21a7dcaab9245ef5cbfc9d6c4bd026925.args.domain = "domain.tld"
    test_upgrade_from.bc9ab6f21a7dcaab9245ef5cbfc9d6c4bd026925.args.language = "en"
    test_upgrade_from.bc9ab6f21a7dcaab9245ef5cbfc9d6c4bd026925.args.admin = "package_checker"

    test_upgrade_from.cd09a41142c55f4d4c0e654574ccb3e9d1ad3f91.name = "Upgrade from 12.1.0"
    test_upgrade_from.cd09a41142c55f4d4c0e654574ccb3e9d1ad3f91.args.domain = "domain.tld"
    test_upgrade_from.cd09a41142c55f4d4c0e654574ccb3e9d1ad3f91.args.language = "en"
    test_upgrade_from.cd09a41142c55f4d4c0e654574ccb3e9d1ad3f91.args.admin = "package_checker"

    test_upgrade_from.1cac04c39ba70cef6571bcb9ae4afca5ccb48ca7.name = "Upgrade from 13.1.0"
    test_upgrade_from.1cac04c39ba70cef6571bcb9ae4afca5ccb48ca7.args.domain = "domain.tld"
    test_upgrade_from.1cac04c39ba70cef6571bcb9ae4afca5ccb48ca7.args.language = "en"
    test_upgrade_from.1cac04c39ba70cef6571bcb9ae4afca5ccb48ca7.args.admin = "package_checker"
