test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.1cac04c39ba70cef6571bcb9ae4afca5ccb48ca7.name = "Upgrade from 13.1.0"
    test_upgrade_from.1cac04c39ba70cef6571bcb9ae4afca5ccb48ca7.args.domain = "domain.tld"
    test_upgrade_from.1cac04c39ba70cef6571bcb9ae4afca5ccb48ca7.args.language = "en"
    test_upgrade_from.1cac04c39ba70cef6571bcb9ae4afca5ccb48ca7.args.admin = "package_checker"
