#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set --key=php_upload_max_filesize --value=100M

ynh_app_setting_set --key=php_memory_limit --value=64M

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

mail="$(ynh_user_get_info --username=$admin --key=mail)"

ynh_app_setting_set --key=password --value="$password"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"
ynh_setup_source --dest_dir="$install_dir/plugins/Ldap_Login" --source_id=ldap_plugin
ynh_setup_source --dest_dir="$install_dir/plugins" --source_id=log_failed_logins_plugin

#=================================================
# SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# SETUP APPLICATION WITH CURL
#=================================================
ynh_script_progression "Setuping application with CURL..."

# Installation with cURL
ynh_local_curl "/install.php?language=$language" \
    "install=true" "dbhost=127.0.0.1" "dbuser=$db_user" "dbpasswd=$db_pwd" "dbname=$db_name" \
    "prefix=" "admin_name=$admin" "admin_pass1=$password" "admin_pass2=$password" "admin_mail=$mail"

#=================================================
# CONFIGURE PIWIGO
#=================================================
ynh_script_progression "Configuring $app..."

# Change local config
ynh_config_add --template="config.inc.php" --destination="$install_dir/local/config/config.inc.php"

# Setup database in local/config/database.inc.php
ynh_config_add --template="database.inc.php" --destination="$install_dir/local/config/database.inc.php"

#=================================================
# ADD LDAP PLUGIN
#=================================================
ynh_script_progression "Configuring LDAP plugin..."

# Activate the LDAP plugin using the WS API

# Login with admin account
ynh_local_curl "/ws.php?format=json" "method=pwg.session.login" "username=$admin" "password=$password"

# Get session token
status=$(ynh_local_curl "/ws.php?format=json" "method=pwg.session.getStatus")
pwg_token=$(jq --raw-output .result.pwg_token <<< "$status")

# Install the Ldap_Login plugin
ynh_local_curl "/ws.php?format=json" "method=pwg.plugins.performAction" "action=install" "plugin=Ldap_Login" "pwg_token=$pwg_token"

# Activate the Ldap_Login plugin
ynh_local_curl "/ws.php?format=json" "method=pwg.plugins.performAction" "action=activate" "plugin=Ldap_Login" "pwg_token=$pwg_token"

# Log out
ynh_local_curl "/ws.php?format=json" "method=pwg.session.logout"

# Edit Ldap_Login plugin configuration
ynh_mysql_db_shell <<< "UPDATE ldap_login_config SET value='ou=users,dc=yunohost,dc=org' WHERE param = 'ld_basedn';
UPDATE ldap_login_config SET value='uid' WHERE param = 'ld_user_attr';
UPDATE ldap_login_config SET value='' WHERE param = 'ld_binddn';
UPDATE ldap_login_config SET value='0' WHERE param = 'allow_new_users';
UPDATE ldap_login_config SET value='0' WHERE param = 'ld_group_user_active';"

#=================================================
# SETUP FAIL2BAN
#=================================================
ynh_script_progression "Configuring Fail2Ban..."

# Configure and activate log_failed_logins plugin
ynh_mysql_db_shell <<< "INSERT INTO plugins (id,state,version) VALUES ('log_failed_logins','active','1.2');"
ynh_mysql_db_shell <<< "INSERT INTO config (param, value) VALUES ('logFailedLoginsFilename','/var/log/${app}FailedLogins.log');"

touch "/var/log/${app}FailedLogins.log"
chown "$app:" "/var/log/${app}FailedLogins.log"

ynh_config_add_fail2ban --logpath="/var/log/${app}FailedLogins.log" --failregex="ip=<HOST>"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
